version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./QIQO.Business.Accounts.Api.sln && dotnet publish ./QIQO.Business.Accounts.Api.sln -c Release -o ./obj/Docker/publish"
